### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by david-daal** [vahemx/Match3GamebyVahemx#1]
Վահե ջան, ճիշտն ասած Մակ-ի վրա չկարողացա քմփայլ անեմ հասկանամ ինչ ա կատարվում։ 
Լիքը քմփայլ եռռոռ ա տալիս

**Comment by vahemx** [comment]
Մակ չունեմ, մակի վրա build չեմ արել Դավիթ ջան։ Windows-ի տակ եմ մենակ արել ու չի բողոքել։ 
Եթե Mac-ով աշխատացնելը պարտադիր ա, ինձ ասա Mac OS version, փորձեմ virtual machine-ով քաշել, գցել, հասկանալ ինչն ա խնդիրը։

**Comment by david-daal** [comment]
Պարտադիր չի, պարզապես ես էլ Windows չունեմ։ Լավ հեսա հասկանամ ինչ ա ուզում

**Comment by david-daal** [comment]
Լավ, աշխատեց
